// Mocks generated by Mockito 5.4.4 from annotations
// in smart_note/test/presentation/bloc/note_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:smart_note/core/error/failures.dart' as _i6;
import 'package:smart_note/core/usecases/usecase.dart' as _i8;
import 'package:smart_note/domain/entities/note.dart' as _i7;
import 'package:smart_note/domain/repositories/note_repository.dart' as _i2;
import 'package:smart_note/domain/usecases/note/create_note.dart' as _i9;
import 'package:smart_note/domain/usecases/note/delete_note.dart' as _i11;
import 'package:smart_note/domain/usecases/note/get_all_notes.dart' as _i4;
import 'package:smart_note/domain/usecases/note/update_note.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNoteRepository_0 extends _i1.SmartFake
    implements _i2.NoteRepository {
  _FakeNoteRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAllNotes].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllNotes extends _i1.Mock implements _i4.GetAllNotes {
  MockGetAllNotes() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNoteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NoteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Note>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>);
}

/// A class which mocks [CreateNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateNote extends _i1.Mock implements _i9.CreateNote {
  MockCreateNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNoteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NoteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> call(
          _i9.CreateNoteParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
            _FakeEither_1<_i6.Failure, _i7.Note>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);
}

/// A class which mocks [UpdateNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateNote extends _i1.Mock implements _i10.UpdateNote {
  MockUpdateNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNoteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NoteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> call(
          _i10.UpdateNoteParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
            _FakeEither_1<_i6.Failure, _i7.Note>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);
}

/// A class which mocks [DeleteNote].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteNote extends _i1.Mock implements _i11.DeleteNote {
  MockDeleteNote() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NoteRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeNoteRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.NoteRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i11.DeleteNoteParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [NoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteRepository extends _i1.Mock implements _i2.NoteRepository {
  MockNoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> createNote(_i7.Note? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNote,
          [note],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
            _FakeEither_1<_i6.Failure, _i7.Note>(
          this,
          Invocation.method(
            #createNote,
            [note],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> getNoteById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNoteById,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
            _FakeEither_1<_i6.Failure, _i7.Note>(
          this,
          Invocation.method(
            #getNoteById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>> getAllNotes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllNotes,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Note>>(
          this,
          Invocation.method(
            #getAllNotes,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>> getPinnedNotes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPinnedNotes,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Note>>(
          this,
          Invocation.method(
            #getPinnedNotes,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>> getArchivedNotes() =>
      (super.noSuchMethod(
        Invocation.method(
          #getArchivedNotes,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Note>>(
          this,
          Invocation.method(
            #getArchivedNotes,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> updateNote(_i7.Note? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
            _FakeEither_1<_i6.Failure, _i7.Note>(
          this,
          Invocation.method(
            #updateNote,
            [note],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> deleteNote(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteNote,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>> searchNotes(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchNotes,
          [query],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Note>>(
          this,
          Invocation.method(
            #searchNotes,
            [query],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Note>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> togglePinNote(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #togglePinNote,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
            _FakeEither_1<_i6.Failure, _i7.Note>(
          this,
          Invocation.method(
            #togglePinNote,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.Note>> toggleArchiveNote(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleArchiveNote,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>.value(
            _FakeEither_1<_i6.Failure, _i7.Note>(
          this,
          Invocation.method(
            #toggleArchiveNote,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.Note>>);
}
